name: check_action

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  check_action:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    container: ${{ matrix.config.cont }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-latest, r: 'devel', bioc: 'devel', cont: "bioconductor/bioconductor_docker:devel", rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/release"}
          - { os: macOS-latest, r: 'latest', bioc: 'release'}
          - { os: windows-latest, r: 'latest', bioc: 'release'}  
    steps: 
      - if: ${{ env.ACT }}
        name: Hack container for local development
        run: |
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs 
      - uses: neurogenomics/rworkflows@master
        with:
          run_bioccheck: 
          run_crancheck: 'true'
          has_testthat: 'true'
          run_covr: 'true'
          run_pkgdown: 'true'
          has_runit: 'false'
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }} 
          run_docker: 'true'
          DOCKER_USERNAME: 'bschilder'
          DOCKER_ORG: 'neurogenomicslab'
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }} 
          runner_os: ${{ runner.os }} 
          cache_version: cache-v1 
          