name: rworkflows_dev_docker-ghtoken-dockerio
'on':
  push:
    branches:
    - master
    - main
    - devel
    - RELEASE_**
    - docker-ghtoken
  pull_request:
    branches:
    - master
    - main
    - devel
    - RELEASE_**
    - docker-ghtoken
jobs:
  rworkflows:
    permissions: write-all
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    container: ${{ matrix.config.cont }}
    strategy:
      fail-fast: ${{ false }}
      matrix:
        config:
        - os: ubuntu-latest
          r: auto
          bioc: release
          cont: ghcr.io/bioconductor/bioconductor_docker:latest
          python-version: 3.12
    steps:
    - uses: neurogenomics/rworkflows@docker-ghtoken
      with:
        run_bioccheck: ${{ false }}
        run_rcmdcheck: ${{ true }}
        as_cran: ${{ true }}
        run_vignettes: ${{ true }}
        has_testthat: ${{ true }}
        run_covr: ${{ true }}
        run_pkgdown: ${{ true }}
        has_runit: ${{ false }}
        # has_latex: ${{ true }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run_docker: ${{ true }}
        docker_registry: docker.io
        docker_org: ${{ secrets.DOCKER_ORG }}
        docker_user: bschilder
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        runner_os: ${{ runner.os }}
        cache_version: cache-v1
        ncpus: 2
        # free_diskspace: ${{ true }}
        # miniforge_variant: false
